apiVersion: v1
appVersion: "1.2.3"
description: A Helm chart for Citrix ADC CPX with Citrix ingress Controller running as sidecar.
name: cnc
version: 1.2.3
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.citrix.com
maintainers:
- name: Priyanka Sharma
  email: priyanka.sharma@citrix.com
- name: Subash Dangal
  email: subash.dangol@citrix.com
