# Default values for citrix-k8s-cpx-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#standaloneCIC: False

#cpxWithCIC: False

# cpximage contains information needed to fetch CPX image
cpx:
  image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-47.103
  pullPolicy: Always

# cicimage contains information needed to fetch CIC image
cic:
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.7.6
  pullPolicy: Always

# openshift is set to true if charts are being deployed in OpenShift environment.
openshift: false

# lsIP contains the Citrix Application Delivery Management (ADM) IP address to license Citrix ADC CPX.
lsIP:

# Specify the Citrix ADM port in lsPort only if you have changed it.
lsPort:

# nsNamespace is the prefix for the resources on the Citrix ADC
nsNamespace:

# Specify the platform license here.
platform:

# license is used accept the terms of the Citrix license
license:
  accept: no

#loginFileName is secret file for NetScaler login
loginFileName:

# nsIP is NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
nsIP: x.x.x.x
nsVIP:

# nsPort is port for NetScaler NITRO
nsPort: 443

# nsProtocol is protocol for NetScaler NITRO
nsProtocol: HTTPS

# logLevel is to set level of CIC Logs
logLevel: DEBUG

# nsNamespace is the prefix for the resources on the Citrix ADC
nsNamespace:

# kubernetesURL is for registering events to kubeapi server
kubernetesURL:

# ingressClass is the name of the Ingress Class
ingressClass:
defaultSSLCert:

#nodeWatch is used for automatic route configuration on NetScaler towards the pod network
nodeWatch: false

exporter:
  required: false
  image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.0
  pullPolicy: Always
  ports:
    containerPort: 8888
