{{- if or .Values.standaloneCIC .Values.cpxWithCIC }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
{{- if .Values.standaloneCIC }}
  name: cic-k8s-role
{{- end}}
{{- if .Values.cpxWithCIC }}
  name: cpx-ingress-k8s-role
{{- end}}
rules:
  - apiGroups: [""]
{{- if .Values.openshift }}
    resources: ["endpoints", "ingresses", "pods", "secrets", "routes", "routes/status", "tokenreviews", "subjectaccessreviews", "nodes", "namespaces"]
{{- else }}
    resources: ["endpoints", "ingresses", "pods", "secrets", "routes", "routes/status", "nodes", "namespaces"]
{{- end}}
    verbs: ["get", "list", "watch"]
  # services/status is needed to update the loadbalancer IP in service status for integrating
  # service of type LoadBalancer with external-dns
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies", "canarycrds", "authpolicies", "ratelimits"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies/status", "canarycrds/status", "authpolicies/status", "ratelimits/status"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["citrix.com"]
    resources: ["vips"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
{{- if .Values.standaloneCIC }}
  name: cic-k8s-role
{{- end}}
{{- if .Values.cpxWithCIC }}
  name: cpx-ingress-k8s-role
{{- end}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if .Values.standaloneCIC }}
  name: cic-k8s-role
{{- end}}
{{- if .Values.cpxWithCIC }}
  name: cpx-ingress-k8s-role
{{- end}}
subjects:
- kind: ServiceAccount
{{- if .Values.standaloneCIC }}
  name: cic-k8s-role
{{- end}}
{{- if .Values.cpxWithCIC }}
  name: cpx-ingress-k8s-role
{{- end}}
  namespace: {{ .Release.Namespace }}
apiVersion: rbac.authorization.k8s.io/v1

---

apiVersion: v1
kind: ServiceAccount
metadata:
{{- if .Values.standaloneCIC }}
  name: cic-k8s-role
{{- end}}
{{- if .Values.cpxWithCIC }}
  name: cpx-ingress-k8s-role
{{- end}}
  namespace: {{ .Release.Namespace }}

---
{{- end}}
